# Generated by Django 3.1.5 on 2023-07-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employapp', '0002_auto_20230720_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
