# Generated by Django 3.1.5 on 2023-07-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employapp', '0003_auto_20230720_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='role',
        ),
        migrations.AlterField(
            model_name='employe',
            name='bonus',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employe',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
